project:
  type: book
  output-dir: docs

date: today
date-format: long

from: markdown+emoji

book:
  title: "How to Calculate and Communicate Extreme Event Attribution"
  author: "Sophia Heinrich"
  page-footer:
    left: "Copyright 2026, Sohia Heinrich"
  chapters:
    - index.qmd # Remove this before you submit your final report!
    - guide.qmd
    - prep.qmd
    - event.qmd
    - estimation.qmd
    - calculation.qmd
    - theoretical.qmd
    - visuals.qmd
    - troubleshooting.qmd
    - references.qmd
  appendices:
    - topic.qmd
    - needs.qmd
    - task-analysis.qmd

bibliography: references.bib

format:
  html:
    highlight-style: a11y
    theme: cosmo
    code-copy: true
  pdf:
    documentclass: scrreprt


